language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - src/lib
notifications:
  email: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - secure: lDCAM01AJ+pn2Ypdpd7av4IMrMYxDIeZjHXpGS7ZS8tVfRmjZtK457D721yBEWSdY+Uqn6Xb9K/Qfxl6UQ4TY7CqojWGt2zyLf75H1Un5IptRLMik0sBnN/x90UbrwimWZcyR3FpnAkq1dRsdS0Tee0jHEt7fBpG3rd2+bVWjJsAm071BSxLpPdwTExOMr2zDsetKEKwV5IoCxRVdyon42zbkwp6lj7PVhE0NnciOMmtpp+jTKDNJ+aaPtAsRu55700Iw9daTdNaLdYZXM30BUj1vf+xtuVpyEU2S7xeBKpM5qNhUlIp2mGSb/EFvoTM2uIKxdh7O2hOxU3ANJAD9p5SWOOjd+V0YPzA34PhxwssPWO30j7n8KbReGwtFGW8hees435TkweGQT1Bg/FmzKSqr9cTKNs00HX1f1a7gX2wIxEMOqWJPllFdOuMrMHlZj5hYpYJ8I63ba0aUi7QzzGoRn72yrNUs+IcishFQ+M5VbhP6IldR51GhVOeL8I7FRvZjRxIL6CRV5djeid8UGCGPy6Ev0yDaDM4cOMDmVmigkLhPjcUUQT6uncbVY2iXzA+Q/TUVJildrtRcMjXJNGmjvCMbnq5VbuYK342G5xOWJ36EDF0n9GBJNZrOYajTZu98BPjMMPMGmenozugBqY580cIdLKmBhAqztqoTDQ=
branches:
  only:
  - master
before_install:
- echo "Before install stage"
- openssl aes-256-cbc -K $encrypted_fc0dffcf456c_key -iv $encrypted_fc0dffcf456c_iv
  -in .travis/travis_ssh_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Alex.Dai(via travis-ci)"
- git config --global user.email "re757575@gmail.com"
install:
- echo "Install stage"
- npm install
- export PATH=$(npm bin):$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- gulp
- mkdir -p resources/android/{splash,icon}
- ionic resources --splash
- ionic resources --icon
- ionic build android
after_success:
- echo "After success stage"
- cd output
- git add .
- git commit -m "[ci skip] Update output from Travis CI"
- git checkout -b travis-ci
- git push --quiet origin travis-ci
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
