language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - src/lib
notifications:
  email: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
branches:
  only:
  - master
before_install:
- echo "Before install stage"
- openssl aes-256-cbc -K $encrypted_fc0dffcf456c_key -iv $encrypted_fc0dffcf456c_iv
  -in .travis/travis_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Alex.Dai(via travis-ci)"
- git config --global user.email "re757575@gmail.com"
install:
- echo "Install stage"
- npm install
- export PATH=$(npm bin):$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- gulp
- mkdir -p resources/android/{splash,icon}
- ionic resources --splash
- ionic resources --icon
- ionic build android
after_success:
- echo "After success stage"
- cd output
- git add .
- git commit -m "[ci skip] Update output from Travis CI"
- git checkout -b travis-ci
- git push --quiet origin travis-ci
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
lure:
- echo "After failure stage"
