language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - src/lib
notifications:
  email: false
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - secure: aFqFFaiXVdIlZFInyXI/nDbn2dTze2imyacL9FqdKS9J2VwIgj67n0H5TUXwuM/UxwkjE4T78J2bmzg0Z6MSsP+pPtE9yBrla/AQA5+dEdB06VWXrH9fhrGt2KjmDSjF+y7mTUtjjw5LGN5dX4isho+vL8r2NQAQBlWjmZbQJJ/uZ9u6J6Ma2KNdf7V7FEl2Vb0S4gDKOht0x0VmpYwdd/CJd1fMchHacVRU8uceRJXvYGZDiBfbsJ3dzCBiImykGYaPoBxUO4JbVGLavhj8Q8rw1Dl+fx0LPW37+XI/Z9NTvizHAQEjsduSD+YemtkiBmSk7Mvh1+cqaMuVApZzJC9aM6vMUQXKKA0tE3j/dXmgjJHPblhTVwFjzcqq/dyg9TEI8eqdoBtbvM340evlVoC66J9zBpZYg0qXw8hN+OYNoVb9i/iJHhENTOjn2Fyf1Z+vJN+sFNVS3UOk3OEz81CDeYo+VQX7Z1q0Zq9vyh5FYnqO+YBODl2lenTTmPsujLNuwoWMtB4ee1NRtJAfCdoHwyOOiuxjBZ/bWZM1jKgtzFuJ+JYdVYS5At2eLZjR3B5DxIjre4qy9oPsEu1ldhO6htCrBjmlDHIj7jAeXTO2opaR9DcxycxrewWJurNYf01TnB9abBRIrrA0z+s/gjk3yeusfwBflcI5r+/9L5A=
before_install:
- echo "Before install stage"
#- openssl aes-256-cbc -K $encrypted_fc0dffcf456c_key -iv $encrypted_fc0dffcf456c_iv
#  -in .travis/travis_ssh_key.enc -out ~/.ssh/id_rsa -d
#- chmod 600 ~/.ssh/id_rsa
#- eval $(ssh-agent)
#- ssh-add ~/.ssh/id_rsa
#- cp .travis/ssh_config ~/.ssh/config
#- git config --global user.name "Alex.Dai(via travis-ci)"
#- git config --global user.email "re757575@gmail.com"
install:
- echo "Install stage"
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" config.xml
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" package.json
- npm -g install cordova ionic
- npm install
- export PATH=$(npm bin):$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
#- git config --global user.name "Alex.Dai (via Travis-CI)"
#- git config --global user.email "re757575@gmail.com"
#- git clone --quiet https://${GH_TOKEN}@github.com/re757575/my-ionic output > /dev/null
- gulp
- mkdir -p resources/android/{splash,icon}
- ionic resources --splash
- ionic resources --icon
- ionic build android
after_success:
- echo "After success stage"
- bash ./.push-release.sh
- export PATH=$(find /usr/local/android-sdk/ -name zipalign -type f| head -1 | sed -e 's/\/zipalign//g'):$PATH
- zipalign -v 4 platforms/android/build/outputs/apk/android-debug.apk platforms/android/build/outputs/apk/android-test.apk
#- cd output
#- git add .
#- git commit -m "[ci skip] Update output from Travis CI"
#- git checkout -b travis-ci
#- git push --force --quiet origin travis-ci > /dev/null 2>&1
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: platforms/android/build/outputs/apk/android-test.apk
  on:
    tags: true
    all_branches: true
after_deploy:
  - echo "After deploy stage"
